### ISSUE TITLE
bassamanator profiles for SV06 with klipper - only part is converted.

### ISSUE THREAD

**Issue by EltrinEU** [theophile/SuperSlicer_to_Orca_scripts#16]
I have tried to convert profiles for SV06 with klipper from bassamanator repository with no luck. Only part of it converts.
There are two profiles - one from prusa, second from super slicer - both gives same result.
https://github.com/bassamanator/Sovol-SV06-firmware/blob/master/misc/PrusaSlicer_config_bundle-SV06-Both.ini
https://github.com/bassamanator/Sovol-SV06-firmware/blob/master/misc/SuperSlicer_config_bundle-SV06-Both.ini

**Comment by theophile** [comment]
The problem is likely due to the fact that the script is designed to convert individual profiles, not config bundles like these. It looks like it wouldn't be very hard to add support for config bundles so I'll add it to the roadmap, but it might be a few days or more before I'm able to take a serious look at it.

In the meantime, there are two things you can try to get these profiles imported now:

1. If you have PrusaSlicer or SuperSlicer installed, import these config bundles there first, then run this script. It should be able to detect the individual profiles after they're imported into Prusa/Super.
2. Manually create individual profiles by cutting and pasting the contents of each config section into its own file. So for example, for the first one, find this line `[print:0.20mm QUALITY SV06 Ellis]` and then starting with the _next_ line, cut and paste the contents into a new file called `0.20mm QUALITY SV06 Ellis.ini`. Stop just before the line `[print:Ellis_Decorative_Standard_15mm3]`, but then repeat the process again starting the line after that, and so on and so forth. Note though that every individual file should contain `# generated by PrusaSlicer 2.6.0+linux-x64-GTK3 on 2023-08-23 at 23:37:05 UTC` as its first line.

**Comment by theophile** [comment]
@EltrinEU, I've pushed some commits that should implement this feature now. I've tested it successfully on both the example files your provided. Please do a `git pull` and give it a try using the `--input` command line option, and let me know if you run into any issues.

**Comment by EltrinEU** [comment]
Hi!, Thank you for the great work! 
The script now converts all the profiles (Hurra! :) ). 

All of the files (filaments, ptinters and processes) lands in one common folder. I will check it on Monday if moving files around by hand will help with proper usage of the converted profiles.

**Comment by theophile** [comment]
> Hi!, Thank you for the great work! The script now converts all the profiles (Hurra! :) ).
> 
> All of the files (filaments, ptinters and processes) lands in one common folder. I will check it on Monday if moving files around by hand will help with proper usage of the converted profiles.

Just pushed a commit to fix that. Please git pull to latest and try again.

**Comment by EltrinEU** [comment]
It's alive :D 
It works now and all files are in their places :) Thank you!
