### ISSUE TITLE
Printer profile gets converted to print profile

### ISSUE THREAD

**Issue by Cloud-Tickler** [theophile/SuperSlicer_to_Orca_scripts#17]
Hello together,

I'm trying to convert Prusa XL Single toolhead configuration files to Orcaslicer. 
But even with an exported MK4 printer profile, the script exports a print profile instead of a printer profile. Any hints why this is happening? In the first dialog I select printer and use the attached file.

Thanks a lot

Dennis
[Prusa_MK4_Demo.txt](https://github.com/theophile/SuperSlicer_to_Orca_scripts/files/12754139/Prusa_MK4_Demo.txt)
![Output_Print](https://github.com/theophile/SuperSlicer_to_Orca_scripts/assets/127838436/7242a3b4-2c00-4638-b5c3-cb67bd3993f8)
![Selection_Printer](https://github.com/theophile/SuperSlicer_to_Orca_scripts/assets/127838436/18cb4d1c-69f0-4edc-a444-dd31d6f54079)

**Comment by theophile** [comment]
I've never seen a printer .ini file like that. Do you know where it came from originally? It has over 300 lines, whereas my PrusaSlicer printer profiles only have about 75. It looks like it contains all the parameters for print, printer, and filament profiles. 

The reason the script is treating it like a print profile is that the script looks at the file and counts the parameters according to what profile type they belong to, and then assumes that the file is of whatever type has the most parameter occurrences. Since this input file has all the parameters for all the profile types, it's treating it like a print profile because print profiles have more parameters. 

I can fix this by having the script treat the input file based on whatever directory it found it in, but I'm still curious how this file came to be.

**Comment by theophile** [comment]
@Cloud-Tickler , I've pushed a commit that should fix this issue, assuming you use the script in interactive mode like you did originally. FYI, if you were to try to convert this file using the `--input` option, it would still treat like like a print profile because it doesn't seem like there's any way to know what kind of profile this is supposed to be other than the name of the folder it's located in.

**Comment by Cloud-Tickler** [comment]
Thanks a lot, great work. I tried the new version and was able to generate a printer config for the MK4 file that succesfully showed up in OrcaSlicer.
I`m using PrusaSlicer 2.6.1 to export the configuration file. Is there a different way? I added a video.
I also managed to export a config file for the Prusa XL single toolhead that shows up in OrcaSlicer. I will do some testing with this. Maybe you wann add the Prusa XL in the selection dialog for the interactive mode as well.

https://github.com/theophile/SuperSlicer_to_Orca_scripts/assets/127838436/3231fb70-ffa0-4739-ae95-c52a9422baa1
![Output_Printer](https://github.com/theophile/SuperSlicer_to_Orca_scripts/assets/127838436/e5012a54-1cbb-4a91-beea-2f92d012b34c)
[Prusa XL Single 060.txt](https://github.com/theophile/SuperSlicer_to_Orca_scripts/files/12762254/Prusa.XL.Single.060.txt)
[Prusa_MK4_Demo.txt](https://github.com/theophile/SuperSlicer_to_Orca_scripts/files/12762255/Prusa_MK4_Demo.txt)

**Comment by theophile** [comment]
Interesting. It shouldn't be necessary to export the config like that at all. You should just be able to run the script and it should find those source .ini files in that directory.

**Comment by Cloud-Tickler** [comment]
As far as I can see, initially this folder is empty if you don't run an export. All system printers that you configure within PrusaSlicer are stored at a different location in one big .ini file.

C:\Users\dh\AppData\Roaming\PrusaSlicer\vendor

If you've run an export, printers will show up as user presets.

![Prusa_System_Printer_Settings](https://github.com/theophile/SuperSlicer_to_Orca_scripts/assets/127838436/9d1f5a6f-c46e-42c2-8a9c-cf42d2f2200b)
![Prusa_Printer_Settings](https://github.com/theophile/SuperSlicer_to_Orca_scripts/assets/127838436/310d1a4f-000f-43bb-a58a-f295ee253baf)

[PrusaResearch.txt](https://github.com/theophile/SuperSlicer_to_Orca_scripts/files/12771840/PrusaResearch.txt)

**Comment by Cloud-Tickler** [comment]
Sadly I got another issue. I don't know what I've changed, but the skript keeps stopping and I can't get to the new dialogue where you choose the printer .
![Failure_message](https://github.com/theophile/SuperSlicer_to_Orca_scripts/assets/127838436/bfa9d296-b22e-45db-8266-a76636780646)

https://github.com/theophile/SuperSlicer_to_Orca_scripts/assets/127838436/54906449-43a7-4b0d-b34c-e6d18c24a659

**Comment by theophile** [comment]
> As far as I can see, initially this folder is empty if you don't run an export. All system printers that you configure within PrusaSlicer are stored at a different location in one big .ini file.

Ah, I see. You're converting the built-in system presets. I have to admit that this use case didn't even occur to me, although it's certainly not unreasonable. I assumed that OrcaSlicer would also have these built-in presets so no need to convert, though I have not actually checked.

**Comment by theophile** [comment]
> Sadly I got another issue. I don't know what I've changed, but the skript keeps stopping and I can't get to the new dialogue where you choose the printer .

This is happening because your OrcaSlicer installations does not have any physical printers set up. I definitely need to implement proper error handling for this situation, but as noted in the [README](https://github.com/theophile/SuperSlicer_to_Orca_scripts#a-note-about-printer-profiles), you need to set up and configure a printer from one of OrcaSlicer's system presets _before_ you run this script, or else the converted printer profile will not have the ability to use or configure network access/gcode uploading.

**Comment by Cloud-Tickler** [comment]
> > As far as I can see, initially this folder is empty if you don't run an export. All system printers that you configure within PrusaSlicer are stored at a different location in one big .ini file.
> 
> Ah, I see. You're converting the built-in system presets. I have to admit that this use case didn't even occur to me, although it's certainly not unreasonable. I assumed that OrcaSlicer would also have these built-in presets so no need to convert, though I have not actually checked.

Yes, exactly. The printer hasn't been imported into OrcaSlicer yet, but I want to use it.  I guess this is not the only printer applicable. So, thanks again for modifying the skript.

**Comment by Cloud-Tickler** [comment]
> > Sadly I got another issue. I don't know what I've changed, but the skript keeps stopping and I can't get to the new dialogue where you choose the printer .
> 
> This is happening because your OrcaSlicer installations does not have any physical printers set up. I definitely need to implement proper error handling for this situation, but as noted in the [README](https://github.com/theophile/SuperSlicer_to_Orca_scripts#a-note-about-printer-profiles), you need to set up and configure a printer from one of OrcaSlicer's system presets _before_ you run this script, or else the converted printer profile will not have the ability to use or configure network access/gcode uploading.

Sorry, seems I have been cleaning up the folders a bit too much because I lost track. Works perfectly again. Thanky you so much.
